set tabstop=2
set ai
set copyindent
set expandtab
set shiftwidth=2
set go-=T
colorscheme turtlechalk
set guifont=Consolas:h18
set ruler
set hlsearch
set smartcase
set history=1000
set undolevels=1000
syntax on
